#!/usr/bin/env python3
"""Phase 1.1 data audit + the zero-training analyses that motivate C4.

Produces reports/03_data_audit.md and the frozen split artifact.

Four questions this answers, in order of how much they change the plan:

1. What do the two splits actually contain? (row counts, nullity, distributions)
2. Can dev's annotator1/2/3 columns be ALIGNED to train's annotator_id
   {85, 86, 89}? If yes, C4's q uses three specifically calibrated bias vectors;
   if no, we must treat the panel as exchangeable, which is weaker but valid.
3. How much macro-F1 does the multi-reference scorer leave on the table? The gap
   between majority-vote selection and the oracle in-set choice IS the headroom
   C4 is chasing. Computable with zero training; if it is small, C4 is dead.
4. Token-length distribution, which decides the sequence-length cap.
"""

from __future__ import annotations

import argparse
import json
from collections import Counter
from pathlib import Path

import numpy as np
import pandas as pd

from higrec.data.labels import (
    CLARITY_LABELS,
    EVASION_LABELS,
    N_EVASION,
    OFFICIAL_CLARITY_OF_LEAF,
    normalize_evasion,
)
from higrec.data.loader import (
    ANNOTATOR_COLUMNS,
    QEvasionSplits,
    annotator_marginals,
    consensus_level,
    derive_dev_consensus_leaf,
    dev_reference_mask,
    load_qevasion,
    write_frozen_splits,
)
from higrec.scoring.official import gold_set_frequency, macro_f1_multireference
from higrec.decision.setmembership import oracle_upper_bound


def section(out: list[str], title: str) -> None:
    out.append(f"\n## {title}\n")


def audit(splits: QEvasionSplits, out_dir: Path) -> list[str]:
    md: list[str] = ["# 03 — Data Audit (Phase 1.1)", ""]
    md.append("Generated by `scripts/audit_data.py`. All numbers computed, none quoted.")

    train, dev = splits.train, splits.dev

    # --- 1. Shape and nullity ---------------------------------------------
    section(md, "1. Splits and column nullity")
    md.append(
        "The HuggingFace split published as `test` is the shared task's "
        "**validation** set. The real 237-row evaluation set is not on HuggingFace.\n"
    )
    md.append("| column | train non-null | dev non-null |")
    md.append("|---|---|---|")
    for col in sorted(set(train.columns) | set(dev.columns)):
        def nn(df: pd.DataFrame) -> str:
            if col not in df.columns:
                return "(absent)"
            n = int((df[col].notna() & (df[col].astype(str).str.strip() != "")).sum())
            return f"{n}/{len(df)}"
        md.append(f"| `{col}` | {nn(train)} | {nn(dev)} |")

    # --- 2. Deduplication --------------------------------------------------
    section(md, "2. Duplicates and multiply-annotated training items")
    key = ["interview_question", "question", "interview_answer"]
    dup_counts = train.groupby(key, dropna=False).size()
    multi = dup_counts[dup_counts > 1]
    md.append(f"- train rows: **{len(train)}**, unique (interview_question, question, answer) "
              f"triples: **{dup_counts.size}**")
    md.append(f"- triples appearing more than once: **{multi.size}** "
              f"(covering {int(multi.sum())} rows)")

    if multi.size:
        # Agreement among the repeated annotations -- C2's secondary sample.
        agree = 0
        for k, n in multi.items():
            rows = train[(train["interview_question"] == k[0])
                         & (train["question"] == k[1])
                         & (train["interview_answer"] == k[2])]
            if rows["evasion_label"].nunique() == 1:
                agree += 1
        md.append(f"- of those, **{agree}** have all annotators agreeing "
                  f"({agree / multi.size:.1%})")
        md.append("\nThese are C2's secondary sample (playbook P2.2 step 1). "
                  "The primary sample remains the 308 multi-reference items.")
    else:
        md.append("\n**No multiply-annotated training items found.** "
                  "C2 therefore rests entirely on the 308 dev items.")

    # --- 3. Label distributions -------------------------------------------
    section(md, "3. Label distributions")
    md.append("### Train (single `evasion_label`)\n")
    md.append("| leaf | count | % |")
    md.append("|---|---|---|")
    tc = train["evasion_label"].value_counts()
    for leaf in EVASION_LABELS:
        n = int(tc.get(leaf, 0))
        md.append(f"| {leaf} | {n} | {n / len(train):.1%} |")

    md.append("\n### Dev (pooled over the three annotator columns)\n")
    pooled = Counter()
    for c in ANNOTATOR_COLUMNS:
        pooled.update(dev[c].map(normalize_evasion).tolist())
    total = sum(pooled.values())
    md.append("| leaf | pooled count | % | train % | shift |")
    md.append("|---|---|---|---|---|")
    for leaf in EVASION_LABELS:
        n = pooled.get(leaf, 0)
        dev_pct, train_pct = n / total, int(tc.get(leaf, 0)) / len(train)
        md.append(f"| {leaf} | {n} | {dev_pct:.1%} | {train_pct:.1%} | "
                  f"{dev_pct - train_pct:+.1%} |")
    md.append("\nLabel shift between splits is the reason Phase 9 applies "
              "importance weighting `w_c = P_dev(c) / P_train(c)`.")

    # --- 4. Annotator marginals and the ALIGNMENT question ----------------
    section(md, "4. Per-annotator marginals, and can dev be aligned to train?")
    marg = annotator_marginals(train)
    md.append("### Train marginals by `annotator_id` (rows sum to 1)\n")
    md.append("| annotator | " + " | ".join(EVASION_LABELS) + " |")
    md.append("|---" * (N_EVASION + 1) + "|")
    for aid, row in marg.iterrows():
        md.append(f"| {aid} | " + " | ".join(f"{row[l]:.3f}" for l in EVASION_LABELS) + " |")

    dev_marg = np.zeros((3, N_EVASION))
    for a, col in enumerate(ANNOTATOR_COLUMNS):
        counts = dev[col].map(normalize_evasion).value_counts()
        for i, leaf in enumerate(EVASION_LABELS):
            dev_marg[a, i] = counts.get(leaf, 0) / len(dev)

    md.append("\n### Dev marginals by column\n")
    md.append("| column | " + " | ".join(EVASION_LABELS) + " |")
    md.append("|---" * (N_EVASION + 1) + "|")
    for a, col in enumerate(ANNOTATOR_COLUMNS):
        md.append(f"| {col} | " + " | ".join(f"{dev_marg[a, i]:.3f}"
                                             for i in range(N_EVASION)) + " |")

    # Alignment by total-variation distance, with and without shift correction.
    train_ids = list(marg.index)
    train_m = marg.values
    md.append("\n### Alignment: total-variation distance, dev column vs train annotator\n")
    md.append("Lower is a better match. **Caveat:** train→dev label shift is a "
              "confound, so a shift-corrected distance is reported alongside. "
              "Correction rescales each train marginal by the pooled dev/train "
              "class ratio and renormalizes, removing the shift common to all "
              "three annotators.\n")

    pooled_dev = np.array([pooled.get(l, 0) for l in EVASION_LABELS], dtype=float)
    pooled_dev /= pooled_dev.sum()
    pooled_train = np.array([tc.get(l, 0) for l in EVASION_LABELS], dtype=float)
    pooled_train /= pooled_train.sum()
    ratio = np.divide(pooled_dev, pooled_train, out=np.ones(N_EVASION),
                      where=pooled_train > 0)

    md.append("| | " + " | ".join(f"train {i}" for i in train_ids) + " |")
    md.append("|---" * (len(train_ids) + 1) + "|")
    raw_tv = np.zeros((3, len(train_ids)))
    cor_tv = np.zeros((3, len(train_ids)))
    for a, col in enumerate(ANNOTATOR_COLUMNS):
        cells = []
        for t in range(len(train_ids)):
            raw = 0.5 * np.abs(dev_marg[a] - train_m[t]).sum()
            shifted = train_m[t] * ratio
            shifted = shifted / shifted.sum()
            cor = 0.5 * np.abs(dev_marg[a] - shifted).sum()
            raw_tv[a, t], cor_tv[a, t] = raw, cor
            cells.append(f"{raw:.3f} / {cor:.3f}")
        md.append(f"| {col} | " + " | ".join(cells) + " |")
    md.append("\n(cell = raw TV / shift-corrected TV)\n")

    # Best one-to-one assignment by corrected distance (3! = 6 permutations).
    from itertools import permutations
    best_perm, best_cost = None, np.inf
    for perm in permutations(range(len(train_ids))):
        cost = sum(cor_tv[a, perm[a]] for a in range(3))
        if cost < best_cost:
            best_cost, best_perm = cost, perm
    md.append("**Best one-to-one assignment** (minimizing total shift-corrected TV):\n")
    for a, col in enumerate(ANNOTATOR_COLUMNS):
        md.append(f"- `{col}` → train annotator **{train_ids[best_perm[a]]}** "
                  f"(TV = {cor_tv[a, best_perm[a]]:.3f})")
    md.append(f"\nTotal cost **{best_cost:.3f}**. Runner-up costs: " + ", ".join(
        f"{sum(cor_tv[a, p[a]] for a in range(3)):.3f}"
        for p in sorted(permutations(range(len(train_ids))),
                        key=lambda p: sum(cor_tv[a, p[a]] for a in range(3)))[1:3]) + ".")
    md.append(
        "\n**How to read this.** A clearly separated best assignment supports "
        "using three specifically calibrated bias vectors in C4's `q`. A "
        "near-tie means the panel must be treated as exchangeable — weaker, but "
        "still valid, since `q` then averages over which annotator is which."
    )

    # --- 5. Consensus structure -------------------------------------------
    section(md, "5. Consensus structure on dev")
    levels = consensus_level(dev)
    md.append("| distinct labels per item | count | % |")
    md.append("|---|---|---|")
    for k in (1, 2, 3):
        n = int((levels == k).sum())
        md.append(f"| {k} | {n} | {n / len(dev):.1%} |")

    leaf_major, has_major = derive_dev_consensus_leaf(dev)
    md.append(f"\n- items with a leaf majority: **{int(has_major.sum())}/{len(dev)}**")
    md.append(f"- items with NO majority (three-way split): "
              f"**{int((~has_major).sum())}**")
    md.append(
        "\nThe organizers resolved three-way splits with an expert adjudicator "
        "but did not release the adjudications. **C4's majority-vote control is "
        "undefined on those items** and must be reported on the "
        f"{int(has_major.sum())}-item subset with the exclusion stated. The "
        "multi-reference scorer itself is well-defined on all 308, since it "
        "needs only the reference set."
    )

    # --- 6. THE HEADROOM: what the multi-reference scorer leaves on the table
    section(md, "6. How much macro-F1 does the scorer leave on the table?")
    md.append(
        "This is the quantity that motivates C4, and it needs **no model and no "
        "training**. Every system published on this task selects a single "
        "consensus label. The scorer rewards landing anywhere in the reference "
        "set, and — because macro-F1 weights all nine classes equally and support "
        "is endogenous — *which* member you pick matters.\n"
    )
    mask = dev_reference_mask(dev)
    freq = gold_set_frequency(mask)

    majority_pred = np.where(has_major, leaf_major, 0)
    majority_f1 = macro_f1_multireference(majority_pred, mask, EVASION_LABELS).macro_f1

    # Most-frequent-class-first: what a well-calibrated consensus model approaches.
    order = np.argsort(-freq)
    greedy_frequent = np.empty(len(dev), dtype=np.int64)
    for i in range(len(dev)):
        members = np.flatnonzero(mask[i])
        greedy_frequent[i] = members[np.argmin([list(order).index(m) for m in members])] \
            if members.size else 0
    frequent_f1 = macro_f1_multireference(greedy_frequent, mask, EVASION_LABELS).macro_f1

    oracle_f1 = oracle_upper_bound(mask, EVASION_LABELS)

    md.append("| selection rule | macro-F1 | what it represents |")
    md.append("|---|---|---|")
    md.append(f"| majority-vote label | **{majority_f1:.4f}** | what a perfect "
              "consensus predictor achieves |")
    md.append(f"| always the most frequent in-set class | **{frequent_f1:.4f}** | "
              "a frequency-biased model that always lands in G |")
    md.append(f"| oracle in-set choice (greedy) | **{oracle_f1:.4f}** | achievable "
              "lower bound on perfect `q` |")
    md.append(f"\n**Headroom = {oracle_f1 - majority_f1:+.4f} macro-F1** over the "
              "majority-vote rule, available to a system that picks *which* "
              "member of the reference set to name, with no change to the "
              "underlying model.")
    md.append(
        "\nThe oracle figure is a **greedy achievable lower bound**, not the true "
        "optimum (`decision.setmembership.oracle_upper_bound` prefers the "
        "currently-rarest in-set member, most-constrained items first). The true "
        "optimum is an assignment problem and is at least this large."
    )
    md.append(
        "\n**Caveat on interpretation.** This is an upper bound on what a perfect "
        "`q` could reach, not a prediction of what C4 will achieve — `q` is "
        "estimated, not given. It bounds the prize, and it tells us whether the "
        "prize is worth chasing at all."
    )

    # --- 7. Token lengths --------------------------------------------------
    section(md, "7. Token-length distribution of [sub-question ; answer]")
    try:
        from transformers import AutoTokenizer

        texts_train = [f"{q} {a}" for q, a in
                       zip(train["question"], train["interview_answer"])]
        md.append("| tokenizer | mean | median | p90 | p95 | p99 | max | >512 | >1024 | >4096 |")
        md.append("|---|---|---|---|---|---|---|---|---|---|")
        for name, model_id in [("DeBERTa-v3-large", "microsoft/deberta-v3-large"),
                               ("ModernBERT-large", "answerdotai/ModernBERT-large")]:
            try:
                tok = AutoTokenizer.from_pretrained(model_id)
                lens = np.array([len(tok(t, add_special_tokens=True)["input_ids"])
                                 for t in texts_train])
                md.append(
                    f"| {name} | {lens.mean():.0f} | {np.median(lens):.0f} | "
                    f"{np.percentile(lens, 90):.0f} | {np.percentile(lens, 95):.0f} | "
                    f"{np.percentile(lens, 99):.0f} | {lens.max()} | "
                    f"{(lens > 512).mean():.1%} | {(lens > 1024).mean():.1%} | "
                    f"{(lens > 4096).mean():.1%} |"
                )
            except Exception as exc:  # noqa: BLE001
                md.append(f"| {name} | tokenizer unavailable: {type(exc).__name__} |")
    except ImportError:
        md.append("`transformers` unavailable; token-length section skipped.")

    md.append(
        "\n**Decision this informs (reasoning.md D-07).** A sequence cap at p95 "
        "captures nearly all of the benefit of removing truncation at a fraction "
        "of the attention cost of a full 8k window."
    )

    # --- frozen splits -----------------------------------------------------
    artifact = write_frozen_splits(splits, out_dir.parent / "configs" / "splits.json")
    section(md, "8. Frozen split artifact")
    md.append("Written to `configs/splits.json`. All future experiments read this "
              "file; splits are never re-derived on the fly.\n")
    md.append("```json")
    md.append(json.dumps(artifact, indent=2))
    md.append("```")

    return md


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache-dir", default="runs/data_cache")
    ap.add_argument("--out", default="reports/03_data_audit.md")
    args = ap.parse_args()

    splits = load_qevasion(cache_dir=args.cache_dir)
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)

    md = audit(splits, out_path.parent)
    out_path.write_text("\n".join(md) + "\n")
    print(f"wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
